# GitLab CI/CD configuration file https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html

stages:
  - package
  - release

package-job:
  stage: package
  script:
    - echo "Packaging wp-offres-emploi-intranet plugin ..."
    - mkdir artifacts
    - cp LICENSE wp-offres-emploi-intranet/LICENSE
    - cp README.md wp-offres-emploi-intranet/README.md
    - cp CHANGELOG.md wp-offres-emploi-intranet/CHANGELOG.md
    - zip -r ./artifacts/wp-offres-emploi-intranet.zip ./wp-offres-emploi-intranet/
    - echo "wp-offres-emploi-intranet plugin packaged."
  artifacts:
    name: '$CI_JOB_NAME $CI_COMMIT_SHORT_SHA'
    untracked: false
    paths:
      - artifacts/

release-job:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Release wp-offres-emploi-intranet plugin $CI_COMMIT_TAG ..."
    - echo "wp-offres-emploi-intranet plugin released."
  dependencies:
    - package-job
  artifacts:
    name: 'wp-offres-emploi-intranet_$CI_COMMIT_TAG'
    untracked: false
    paths:
      - artifacts/
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
      - name: 'wp-offres-emploi-intranet $CI_COMMIT_TAG'
        url: 'https://git.manche.io/wordpress/wp-offres-emploi-intranet/-/jobs/$CI_JOB_ID/artifacts/download'
        link_type: package